# Generated by Django 3.2.16 on 2026-04-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='category',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='wrapper',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='IceCream',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='Wrapper',
        ),
    ]
